import { PropsWithChildren, ReactNode } from 'react'

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import AppProvider from '@pages/AppProvider'

import { Navbar } from '@widgets/Navbar'
import { Sidebar } from '@widgets/Sidebar'

import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<PropsWithChildren<HTMLElement>>) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<Navbar />
				<AppProvider>
					<Sidebar />
					{children}
				</AppProvider>
			</body>
		</html>
	)
}
